[book]
authors = ["Robert Masen"]
multilingual = false
src = "src"
title = "Evaluating Parser Options"
[build]
build-dir = "doc"
[output.html]
theme = "src/theme"

[preprocessor.presentation-preprocessor]